"use client";

/*
 * Network Attack Path Analyzer
 * Author: MD Jubayer Khan Akash
 * Project version: 0.7.0
 */

import { useMemo, useState } from "react";

type Vulnerability = { id: string; severity: string; score: number; description: string };
type Node = { id: string; name: string; type: string; zone: string; criticality: number; exposed: boolean; open_ports: number[]; vulnerabilities: Vulnerability[]; x: number; y: number };
type Edge = { source: string; target: string; protocol: string; port?: number | null; allowed: boolean; description?: string };
type Network = { nodes: Node[]; edges: Edge[] };
type RiskBreakdown = { exposure: number; vulnerability: number; criticality: number; service_exposure: number; segmentation: number; path_complexity: number };
type PathResult = { path: string[]; hops: number; rank: number; risk_score: number; severity: string; reasons: string[]; risk_breakdown: RiskBreakdown };
type Analysis = { source: string; target: string; total_paths: number; paths: PathResult[] };
type Report = { title: string; source: string; target: string; summary: { nodes: number; allowed_edges: number; possible_paths: number; max_risk: number; average_risk: number; severity_counts: Record<string, number>; critical_assets: number; vulnerable_assets: number }; top_paths: PathResult[]; remediations: { priority: string; category: string; asset: string; action: string }[]; methodology: string[] };
type AIExplanation = { mode: string; executive_summary: string; threat_story: string; key_risks: {factor:string; score:number; why:string}[]; priority_actions: {priority:string; action:string; asset:string}[]; analyst_notes: string[]; llm_explanation?: string | null };
type Simulation = { compromised: string; target: string; reachable: boolean; baseline_path_count: number; post_compromise_path_count: number; baseline_max_risk: number; post_compromise_max_risk: number; risk_delta: number; paths: PathResult[]; findings: string[] };

const API_BASE = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

const initialNetwork: Network = {
  nodes: [
    { id: "internet", name: "Internet", type: "external", zone: "external", criticality: 10, exposed: true, open_ports: [], vulnerabilities: [], x: 100, y: 180 },
    { id: "firewall", name: "Edge Firewall", type: "firewall", zone: "dmz", criticality: 8, exposed: true, open_ports: [443], vulnerabilities: [], x: 300, y: 180 },
    { id: "web", name: "Web Server", type: "server", zone: "dmz", criticality: 8, exposed: true, open_ports: [22, 80, 443], vulnerabilities: [{ id: "CVE-DEMO-001", severity: "high", score: 8.5, description: "Demo vulnerability" }], x: 500, y: 100 },
    { id: "vpn", name: "VPN Gateway", type: "gateway", zone: "dmz", criticality: 7, exposed: true, open_ports: [443], vulnerabilities: [], x: 500, y: 270 },
    { id: "pc01", name: "Employee PC", type: "workstation", zone: "internal", criticality: 6, exposed: false, open_ports: [445], vulnerabilities: [{ id: "CVE-DEMO-002", severity: "medium", score: 6.5, description: "Demo endpoint vulnerability" }], x: 700, y: 270 },
    { id: "db", name: "Customer Database", type: "database", zone: "restricted", criticality: 10, exposed: false, open_ports: [3306], vulnerabilities: [], x: 900, y: 180 }
  ],
  edges: [
    { source: "internet", target: "firewall", protocol: "TCP", port: 443, allowed: true }, { source: "firewall", target: "web", protocol: "TCP", port: 443, allowed: true }, { source: "firewall", target: "vpn", protocol: "TCP", port: 443, allowed: true }, { source: "web", target: "db", protocol: "TCP", port: 3306, allowed: true }, { source: "vpn", target: "pc01", protocol: "TCP", port: 445, allowed: true }, { source: "pc01", target: "db", protocol: "TCP", port: 3306, allowed: true }, { source: "internet", target: "db", protocol: "TCP", port: 3306, allowed: false }
  ]
};

function emptyNode(id: string, index: number): Node { return { id, name: "New Asset", type: "server", zone: "internal", criticality: 5, exposed: false, open_ports: [], vulnerabilities: [], x: 180 + (index % 4) * 200, y: 80 + Math.floor(index / 4) * 150 }; }

export default function Home() {
  const [network, setNetwork] = useState<Network>(initialNetwork), [selectedId, setSelectedId] = useState("web"), [source, setSource] = useState("internet"), [target, setTarget] = useState("db"), [analysis, setAnalysis] = useState<Analysis | null>(null), [simulation, setSimulation] = useState<Simulation | null>(null), [report, setReport] = useState<Report | null>(null), [ai, setAi] = useState<AIExplanation | null>(null), [aiLoading, setAiLoading] = useState(false), [error, setError] = useState(""), [edgeSource, setEdgeSource] = useState("firewall"), [edgeTarget, setEdgeTarget] = useState("web"), [edgePort, setEdgePort] = useState("443"), [edgeAllowed, setEdgeAllowed] = useState(true), [compromised, setCompromised] = useState("web"), [simLoading, setSimLoading] = useState(false);
  const selected = network.nodes.find(n => n.id === selectedId) ?? network.nodes[0];
  const nodeMap = useMemo(() => new Map(network.nodes.map(n => [n.id, n.name])), [network.nodes]);
  const criticalAssets = network.nodes.filter(n => n.criticality >= 9).length, vulnerableNodes = network.nodes.filter(n => n.vulnerabilities.length).length, blockedEdges = network.edges.filter(e => !e.allowed).length;
  const payloadNetwork = () => ({ ...network, nodes: network.nodes.map(({ x, y, ...n }) => n) });
  function updateSelected(patch: Partial<Node>) { if (selected) setNetwork(prev => ({ ...prev, nodes: prev.nodes.map(n => n.id === selected.id ? { ...n, ...patch } : n) })); }
  function addNode() { const node = emptyNode(`asset-${network.nodes.length + 1}`, network.nodes.length); setNetwork(prev => ({ ...prev, nodes: [...prev.nodes, node] })); setSelectedId(node.id); setSource(node.id); setCompromised(node.id); }
  function deleteNode() { if (!selected || network.nodes.length <= 2) return; setNetwork(prev => ({ nodes: prev.nodes.filter(n => n.id !== selected.id), edges: prev.edges.filter(e => e.source !== selected.id && e.target !== selected.id) })); const remaining = network.nodes.find(n => n.id !== selected.id); if (remaining) { setSelectedId(remaining.id); setSource(remaining.id); setCompromised(remaining.id); } }
  function addEdge() { if (!edgeSource || !edgeTarget || edgeSource === edgeTarget) return; if (network.edges.some(e => e.source === edgeSource && e.target === edgeTarget)) return setError("That connection already exists."); setError(""); setNetwork(prev => ({ ...prev, edges: [...prev.edges, { source: edgeSource, target: edgeTarget, protocol: "TCP", port: Number(edgePort) || null, allowed: edgeAllowed, description: "Configured in topology editor" }] })); }
  function deleteEdge(index: number) { setNetwork(prev => ({ ...prev, edges: prev.edges.filter((_, i) => i !== index) })); }
  async function analyze() { setError(""); setAnalysis(null); try { const r = await fetch(`${API_BASE}/api/analyze`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({network:payloadNetwork(),source,target,max_paths:20}) }); const d=await r.json(); if(!r.ok) throw new Error(d.detail??"Analysis failed"); setAnalysis(d); } catch(e){setError(e instanceof Error?e.message:"Unable to reach backend");} }
  async function generateReport() { setError(""); setReport(null); try { const r = await fetch(`${API_BASE}/api/report`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({network:payloadNetwork(),source,target,max_paths:20}) }); const d=await r.json(); if(!r.ok) throw new Error(d.detail??"Report generation failed"); setReport(d); } catch(e){setError(e instanceof Error?e.message:"Unable to reach backend");} }
  async function explainWithAI() { setError(""); setAi(null); setAiLoading(true); try { const r = await fetch(`${API_BASE}/api/ai/explain`, { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({network:payloadNetwork(),source,target,max_paths:20}) }); const d=await r.json(); if(!r.ok) throw new Error(d.detail??"AI explanation failed"); setAi(d); } catch(e){setError(e instanceof Error?e.message:"Unable to reach backend");} finally{setAiLoading(false);} }
  function downloadReport() { if(!report) return; const blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url; a.download=`network-security-report-${report.source}-${report.target}.json`; a.click(); URL.revokeObjectURL(url); }
  function printReport() { if(!report) return; window.print(); }
  async function runSimulation() { setError(""); setSimulation(null); setSimLoading(true); try { const r=await fetch(`${API_BASE}/api/simulate/compromise`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({network:payloadNetwork(),source,target,compromised,max_paths:20})}); const d=await r.json(); if(!r.ok) throw new Error(d.detail??"Simulation failed"); setSimulation(d); } catch(e){setError(e instanceof Error?e.message:"Unable to reach backend");} finally{setSimLoading(false);} }
  return <main className="container">
    <header className="hero"><div><p className="eyebrow">DEFENSIVE SECURITY LAB · FINAL</p><h1>Network Attack Path Analyzer</h1><p className="muted">Model a network, assess risk, simulate compromise, validate policy changes, generate reports, and explain findings.</p></div><div className="button-row"><button onClick={explainWithAI} disabled={aiLoading}>{aiLoading?"Analyzing…":"✦ AI Security Explanation"}</button><button className="primary" onClick={addNode}>＋ Add Asset</button></div></header>
    <section className="grid"><div className="stat"><span>Network nodes</span><strong>{network.nodes.length}</strong></div><div className="stat"><span>Critical assets</span><strong>{criticalAssets}</strong></div><div className="stat"><span>Vulnerable nodes</span><strong>{vulnerableNodes}</strong></div><div className="stat"><span>Blocked rules</span><strong>{blockedEdges}</strong></div></section>
    <section className="workspace"><div className="card topology-card"><div className="section-head"><div><p className="eyebrow">TOPOLOGY EDITOR</p><h2>Network map</h2></div><span className="hint">Click an asset to edit it</span></div><div className="canvas-wrap"><svg className="topology" viewBox="0 0 1000 390"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" /></marker></defs>{network.edges.map((e,i)=>{const a=network.nodes.find(n=>n.id===e.source),b=network.nodes.find(n=>n.id===e.target);if(!a||!b)return null;return <g key={i} className={e.allowed?"edge":"edge blocked"}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y} markerEnd="url(#arrow)"/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-7}>{e.protocol}{e.port?`:${e.port}`:""}</text></g>})}{network.nodes.map(n=><g key={n.id} className={`node ${selectedId===n.id?"selected":""}`} onClick={()=>setSelectedId(n.id)}><circle cx={n.x} cy={n.y} r="34"/><text x={n.x} y={n.y-3}>{n.type.toUpperCase().slice(0,10)}</text><text className="node-name" x={n.x} y={n.y+52}>{n.name}</text><text className="node-zone" x={n.x} y={n.y+68}>{n.zone} · C{n.criticality}</text></g>)}</svg></div>
      <div className="edge-builder"><div><p className="eyebrow">CONNECTION BUILDER</p><h3>Add firewall / network rule</h3></div><div className="controls"><label>From<select value={edgeSource} onChange={e=>setEdgeSource(e.target.value)}>{network.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>To<select value={edgeTarget} onChange={e=>setEdgeTarget(e.target.value)}>{network.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Port<input value={edgePort} onChange={e=>setEdgePort(e.target.value)} type="number" min="1" max="65535"/></label><label className="check"><input type="checkbox" checked={edgeAllowed} onChange={e=>setEdgeAllowed(e.target.checked)}/> Allowed</label><button onClick={addEdge}>Add connection</button></div></div>
      <div className="rules"><h3>Configured connections</h3>{network.edges.map((e,i)=><div className="rule" key={`${e.source}-${e.target}-${i}`}><span>{nodeMap.get(e.source)} → {nodeMap.get(e.target)}</span><small>{e.protocol}{e.port?`:${e.port}`:""} · {e.allowed?"ALLOW":"BLOCK"}</small><button className="danger-link" onClick={()=>deleteEdge(i)}>Remove</button></div>)}</div>
    </div><aside className="card inspector"><div className="section-head"><div><p className="eyebrow">ASSET INSPECTOR</p><h2>Security context</h2></div></div>{selected&&<div className="form-grid"><label>Asset ID<input value={selected.id} disabled/></label><label>Name<input value={selected.name} onChange={e=>updateSelected({name:e.target.value})}/></label><label>Type<select value={selected.type} onChange={e=>updateSelected({type:e.target.value})}><option>server</option><option>firewall</option><option>gateway</option><option>workstation</option><option>database</option><option>external</option></select></label><label>Zone<select value={selected.zone} onChange={e=>updateSelected({zone:e.target.value})}><option>external</option><option>dmz</option><option>internal</option><option>restricted</option></select></label><label>Criticality (1-10)<input type="number" min="1" max="10" value={selected.criticality} onChange={e=>updateSelected({criticality:Math.max(1,Math.min(10,Number(e.target.value)))})}/></label><label className="check"><input type="checkbox" checked={selected.exposed} onChange={e=>updateSelected({exposed:e.target.checked})}/> Internet exposed</label><label className="wide">Open ports<input value={selected.open_ports.join(", ")} onChange={e=>updateSelected({open_ports:e.target.value.split(",").map(v=>Number(v.trim())).filter(v=>v>0)})}/></label><label className="wide">Vulnerabilities (JSON)<textarea value={JSON.stringify(selected.vulnerabilities,null,2)} onChange={e=>{try{updateSelected({vulnerabilities:JSON.parse(e.target.value)})}catch{}}}/></label></div>}<button className="danger" onClick={deleteNode}>Delete selected asset</button></aside></section>
    <section className="card"><div className="section-head"><div><p className="eyebrow">PATH ANALYSIS</p><h2>Find risky routes</h2></div><div className="button-row"><button className="primary" onClick={analyze}>Run Analysis</button><button onClick={generateReport}>Generate Security Report</button></div></div><div className="controls"><label>Source<select value={source} onChange={e=>setSource(e.target.value)}>{network.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Target<select value={target} onChange={e=>setTarget(e.target.value)}>{network.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label></div></section>
    <section className="card simulator"><div className="section-head"><div><p className="eyebrow">WHAT-IF SIMULATOR</p><h2>Compromise a node</h2><p className="muted">Assume one asset is compromised and measure whether the selected target becomes reachable.</p></div><button className="primary" onClick={runSimulation} disabled={simLoading}>{simLoading?"Simulating…":"Simulate Compromise"}</button></div><div className="controls"><label>Compromised asset<select value={compromised} onChange={e=>setCompromised(e.target.value)}>{network.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Target<select value={target} onChange={e=>setTarget(e.target.value)}>{network.nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label></div>{simulation&&<div className="simulation-result"><div className="sim-stats"><div><span>Reachable</span><strong>{simulation.reachable?"YES":"NO"}</strong></div><div><span>Before</span><strong>{simulation.baseline_path_count} paths</strong></div><div><span>After compromise</span><strong>{simulation.post_compromise_path_count} paths</strong></div><div><span>Risk delta</span><strong>{simulation.risk_delta>0?`+${simulation.risk_delta}`:simulation.risk_delta}</strong></div></div><ul>{simulation.findings.map((f,i)=><li key={i}>{f}</li>)}</ul>{simulation.paths.map(item=><article className="path" key={`${item.rank}-${item.path.join("-")}`}><div className="path-top"><strong>#{item.rank} · {item.severity.toUpperCase()}</strong><span>{item.risk_score}/100 · {item.hops} hops</span></div><p className="route">{item.path.map(id=>nodeMap.get(id)).join(" → ")}</p></article>)}</div>}</section>
    {ai&&<section className="card ai-panel"><div className="section-head"><div><p className="eyebrow">AI SECURITY EXPLANATION</p><h2>Security Copilot</h2><p className="muted">Explainable interpretation of the modeled risk. Numeric scores remain authoritative.</p></div><span className="badge">{ai.mode}</span></div><div className="ai-summary"><h3>Executive summary</h3><p>{ai.executive_summary}</p><h3>Threat story</h3><p>{ai.threat_story}</p></div><div className="report-columns"><div><h3>Key risks</h3>{ai.key_risks.map((r,i)=><article className="remediation" key={i}><div><strong>{r.factor}</strong><span>{r.score} points</span></div><p>{r.why}</p></article>)}</div><div><h3>Priority actions</h3>{ai.priority_actions.map((r,i)=><article className="remediation" key={i}><div><strong>{r.priority.toUpperCase()}</strong><span>{r.asset}</span></div><p>{r.action}</p></article>)}</div></div>{ai.llm_explanation&&<div className="ai-llm"><h3>LLM interpretation</h3><p>{ai.llm_explanation}</p></div>}<div><h3>Analyst notes</h3><ul>{ai.analyst_notes.map((n,i)=><li key={i}>{n}</li>)}</ul></div></section>}
    {report&&<section className="card report"><div className="section-head"><div><p className="eyebrow">SECURITY ASSESSMENT REPORT</p><h2>{report.title}</h2><p className="muted">{nodeMap.get(report.source)} → {nodeMap.get(report.target)}</p></div><div className="button-row"><button onClick={downloadReport}>Export JSON</button><button onClick={printReport}>Print / Save PDF</button></div></div><div className="report-grid"><div><span>Possible paths</span><strong>{report.summary.possible_paths}</strong></div><div><span>Maximum risk</span><strong>{report.summary.max_risk}/100</strong></div><div><span>Average risk</span><strong>{report.summary.average_risk}/100</strong></div><div><span>Critical assets</span><strong>{report.summary.critical_assets}</strong></div><div><span>Vulnerable assets</span><strong>{report.summary.vulnerable_assets}</strong></div><div><span>Allowed connections</span><strong>{report.summary.allowed_edges}</strong></div></div><div className="report-columns"><div><h3>Top attack paths</h3>{report.top_paths.map(item=><article className="path" key={`report-${item.rank}`}><div className="path-top"><strong>#{item.rank} · {item.severity.toUpperCase()}</strong><span>{item.risk_score}/100</span></div><p className="route">{item.path.map(id=>nodeMap.get(id)).join(" → ")}</p></article>)}</div><div><h3>Prioritized remediation</h3>{report.remediations.length===0?<p className="muted">No remediation items were generated.</p>:report.remediations.map((r,i)=><article className="remediation" key={i}><div><strong>{r.priority.toUpperCase()} · {r.category}</strong><span>{r.asset}</span></div><p>{r.action}</p></article>)}</div></div><div><h3>Methodology</h3><ul>{report.methodology.map((m,i)=><li key={i}>{m}</li>)}</ul></div></section>}
    {error&&<p className="error">{error}</p>}{analysis&&<section className="card"><div className="result-head"><div><p className="eyebrow">ANALYSIS RESULT</p><h2>{analysis.total_paths} possible path(s)</h2></div><span className="badge">{nodeMap.get(analysis.source)} → {nodeMap.get(analysis.target)}</span></div>{analysis.paths.map(item=><article className="path" key={`${item.rank}-${item.path.join("-")}`}><div className="path-top"><strong>#{item.rank} · {item.severity.toUpperCase()}</strong><span>{item.risk_score}/100 · {item.hops} hops</span></div><p className="route">{item.path.map(id=>nodeMap.get(id)).join(" → ")}</p><div className="risk-breakdown">{Object.entries(item.risk_breakdown).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><strong>{value}</strong></div>)}</div><ul>{item.reasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul></article>)}</section>}
    <footer className="project-footer">Network Attack Path Analyzer · Developed by MD Jubayer Khan Akash · v0.7.0</footer>
  </main>;
}
